find_library (LZ4_LIBRARY lz4)
find_path (LZ4_INCLUDE_DIR lz4.h)
include (FindPackageHandleStandardArgs)
find_package_handle_standard_args (LZ4 DEFAULT_MSG LZ4_LIBRARY LZ4_INCLUDE_DIR)
mark_as_advanced (LZ4_INCLUDE_DIR LZ4_LIBRARY)